[theme]
base                     = "light"
backgroundColor          = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
primaryColor             = "#0033A0"
textColor                = "#0A0F1E"

[server]
headless   = true
runOnSave  = true

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = false